### PR TITLE
Use image paths as names for landing page.

### PR DESCRIPTION
**Pull request by etefera**
image

### CODE REVIEW

**Review by mengqiy — APPROVED** [review]
Thanks!

**Comment by runewake2** [comment]
Recommend also including the landing pages for the functions. Does this do that?

**Comment by etefera** [comment]
> Recommend also including the landing pages for the functions. Does this do that?
> 
> Ex. there are no image paths on the children pages: https://catalog.kpt.dev/starlark/v0.1/

No, that's handled at the `README.md` level for each function.

**Comment by frankfarzan** [comment]
I think this reduces the readability as all functions now have common prefix (`gcr.io/kpt-fn`). Human eye mostly notices the first few characters of words. I suggest, showing the container image in a different context, for example in the usage docs.

**Comment by mengqiy** [comment]
What about adding a new column called `image` in the landing page?

**Comment by frankfarzan** [comment]
Is there a particular reason, it can't be in the function use doc somewhere here: https://screenshot.googleplex.com/5iSDN7PE3BfBwUD

**Comment by mengqiy** [comment]
I think it is possible.
@etefera Can you please confirm? And also how much work is it?

**Comment by etefera** [comment]
We can automatically stick it somewhere there, but I'm not sure why that would be preferred in this case over having the images written into the `README.md`s by the titles.

**Comment by mengqiy** [comment]
> the images written into the README.mds by the titles.

You mean something like:
```
# apply-setters
image: `gcr.io/kpt-fn/apply-setters`

### Overview
...
```

I don't have strong opinion here. It should be OK as long as it looks reasonable good.

**Comment by etefera** [comment]
> > the images written into the README.mds by the titles.
> 
> @etefera You mean something like:
> 
> ```
> # apply-setters
> image: `gcr.io/kpt-fn/apply-setters`
> 
> ### Overview
> ...
> ```
> 
> I don't have strong opinion here. It should be OK as long as it looks reasonable good.

Yeah, something like that. I think it's probably better to handle at the function `README` level.

**Pull request merged**
