### PR TITLE
use kpt from main branch

### PR DESCRIPTION
**Pull request by mengqiy**

### CODE REVIEW

**Review by frankfarzan — APPROVED** [review]

**Review by droot — APPROVED** [review]

**Comment by mengqiy** [comment]
Change it to install from `main` explicitly. Otherwise it still installs the pre-v1 kpt.

**Comment by frankfarzan** [comment]
> Change it to install from `main` explicitly. Otherwise it still installs the pre-v1 kpt.

This shouldn't be the case. Are you sure?

**Comment by frankfarzan** [comment]
> > Change it to install from `main` explicitly. Otherwise it still installs the pre-v1 kpt.
> 
> This shouldn't be the case. Are you sure?

You're right. We should change this as these instructions are incorrect now:

https://kpt.dev/installation/?id=source

**Comment by mengqiy** [comment]
>You're right. We should change this as these instructions are incorrect now:

I saw you have already updated it.

I guess if we rename `next` to `master` instead of `main`, it should work and we don't need to specify `@main`.

**Pull request merged**
