### PR TITLE
Merge master to set-namespace/v0.3

### PR DESCRIPTION
**Pull request by yuwenma**

### CODE REVIEW

**Comment by yuwenma** [comment]
@sdowell This PR is rebased from master and contains your fix [`942a12a` (#823)](https://github.com/GoogleContainerTools/kpt-functions-catalog/pull/823/commits/942a12a3123acf6199b40b0684ea6ba0c2ce24f6). But it looks like the veirfy-doc still fails. Could you take a look?

**Comment by sdowell** [comment]
@yuwenma What is the goal of merging master into this release branch?

The `update-function-docs` target still needs to be ran to generate the release commit that will satisfy the `verify-docs` script

**Comment by yuwenma** [comment]
rerun `make update-function-docs` @sdowell

**Review by sdowell — APPROVED** [review]
Approved, but please consider whether the merge commit is needed

**Comment by yuwenma** [comment]
> Approved, but please consider whether the merge commit is needed

I tried both rebasing to master and cherry-picked the specific git commits,  and run `make update-function-docs` as @sdowell suggested. But it looks like the CI cannot find the local image gcr.io/kpt-fn/set-namespace:v0.3.3

Shall I bypass the CI test?

**Comment by yuwenma** [comment]
Force merging since the failure is caused by a version drift (should be fixed once https://github.com/GoogleContainerTools/kpt-functions-catalog/pull/828 merges in): 

- Either rebase to master or cherry-picking the 7841e2090f6d01260b1b9ba4660c310528ca5477 fails verify-docs. 
   From @sdowell, this is due to the fact that the broken docs merges in before fix #821 takes action. As a one-off fix to the version drift, we shall run `git checkout upstream/master # checkout latest make target from tip`
and `RELEASE_BRANCH=set-namespace/v0.3 make update-function-docs # generate commit to update docs for release branch` 

- I ran the suggested command and fix conflicts. Both `sourceURL` gcr.io/kpt-fn/set-namespace:v0.3 and gcr.oi/kpt-fn/set-namespace:v0.3.3 fail the ci/e2e test with the following failure 
```bash
        [RUNNING] "gcr.io/kpt-fn/set-namespace:v0.3.3"
        [FAIL] "gcr.io/kpt-fn/set-namespace:v0.3.3" in 0s
          Stderr:
            "docker: Error response from daemon: No such image: gcr.io/kpt-fn/set-namespace:v0.3.3."
            "See 'docker run --help'."
          Exit code: 125
```  
See full log [here](https://github.com/GoogleContainerTools/kpt-functions-catalog/runs/6067908022?check_suite_focus=true)

**Pull request merged**
