### PR TITLE
add wasm functionality to apply-replacements

### PR DESCRIPTION
**Pull request by wmuizelaar**
Like https://github.com/GoogleContainerTools/kpt-functions-catalog/pull/898 - this PR adds wasm functionality to the apply-replacements function.

### CODE REVIEW

**Comment by droot** [comment]
Thanks for submitting the PR.

@natasha41575 can you pl. take a at this.

**Comment by natasha41575** [comment]
@droot @yuwenma could one of you merge this? I don't have owner permissions

**Review by yuwenma — APPROVED** [review]

**Comment by wmuizelaar** [comment]
Can this one be merged?

**Comment by yuwenma** [comment]
@wmuizelaar @natasha41575 Thanks for the reminder. I'll release this function by the end of tomorrow.

**Pull request merged**
