### PR TITLE
bump up go-yaml version that includes roundtripping fixes

### PR DESCRIPTION
**Pull request by droot**
The latest release of `go-yaml` includes fixes related to roundtripping of comments in YAML. This PR bumps up the version to include those fixes.

### CODE REVIEW

**Comment by droot** [comment]
/cc @natasha41575 @Shell32-Natsu @mengqiy 

I have done minimum testing. But I think we should have tests to test roundtripping of comments etc. 

We probably want to do this for other functions we all. Apologies for doing the minimum here :)

**Comment by droot** [comment]
https://github.com/GoogleContainerTools/kpt/pull/1699#discussion_r608260765

**Review by Shell32-Natsu — APPROVED** [review]
lgtm

**Comment by droot** [comment]
https://github.com/GoogleContainerTools/kpt/issues/1706

**Review by mengqiy — APPROVED** [review]

**Pull request merged**
