### PR TITLE
docs: Update tags for go/render-helm-chart/v0.2.3

### PR DESCRIPTION
**Pull request by natasha41575**

### CODE REVIEW

**Review by droot — APPROVED** [review]

**Comment by natasha41575** [comment]
It looks like the CD job for pushing images is broken: https://github.com/GoogleContainerTools/kpt-functions-catalog/actions/workflows/after-tag-with-version.yaml

Will merge this PR after getting guidance on how to push to the image

**Comment by sdowell** [comment]
I think that is expected to fail https://github.com/GoogleContainerTools/kpt-functions-catalog/pull/952/files#r1024392970

cc @justinsb

**Comment by natasha41575** [comment]
@sdowell Do you have any context on why the CD job exists if it is expected to fail?

**Comment by natasha41575** [comment]
@sdowell Thanks for the context! So is it expected to fail but still push the image to the container registry? Seems like the new render-helm-chart function tag didn't get pushed either

**Comment by sdowell** [comment]
IIRC @justinsb was working on a new CD approach that was designed for a subset of functions he was working on. I don't have much more context than that, but it looks like that workflow doesn't work for any of the older functions which use the previous pattern of the Makefile in the parent directory.

I don't recall how exactly the old release flow works, I think there is an internal release pipeline that builds/publishes the images

**Pull request closed without merging**
