### PR TITLE
update apply-replacements dependencies

### PR DESCRIPTION
**Pull request by natasha41575**
Nonblocking, but I realized that there were some features added to kustomize `replacements` in more recent releases. Updating apply-replacements so that we can get those features.

### CODE REVIEW

**Review by yuwenma — APPROVED** [review]

**Comment by yuwenma** [comment]
FYI, apply-replacement is built into porch. So this change won't be automatically updated in porch. Is this needed for the fishfooding? I doubt @mengqiy has finished the apply-replacement builtin updates. Leave to you guys to decide whether to update porch.

**Comment by natasha41575** [comment]
> Is this needed for the fishfooding?

Not needed for fishfooding session tomorrow, the new features are not critical but the upgrade here will keep us consistent with kustomize docs.

**Comment by natasha41575** [comment]
https://github.com/kubernetes-sigs/kustomize/pull/4574 will fix the CI failure here.

**Comment by yuwenma** [comment]
Once  fixing the e2e-ci, feel free to merge

**Comment by natasha41575** [comment]
Found another issue with replacements, https://github.com/kubernetes-sigs/kustomize/pull/4667 should fix

**Comment by natasha41575** [comment]
FYI @yuwenma @mengqiy this picks up some new features and bug fixes for the replacement transformer, most notably the wildcard match for fieldPath syntax (e.g. `spec.template.spec.containers.*.env`). I think this is worth releasing a new version of the function whenever you get the chance.

**Pull request merged**
