### PR TITLE
Separate api layer apply-setters

### PR DESCRIPTION
**Pull request by phanimarupaka**
This PR is to move `apply-setters` api layer to `applysetters` package so that it is reusable. `main.go` deals with the cmd/function framework. `apply-setters/api` package holds core reusable logic. 
Addresses https://github.com/GoogleContainerTools/kpt/issues/1832

This PR also addresses https://github.com/GoogleContainerTools/kpt/issues/1870

cc @yhrn

### CODE REVIEW

**Comment by yhrn** [comment]
@phanimarupaka Thank you for getting to this so quickly. Can I also request that when you create a new release of the function to make sure that the tag matches the actual repo path? The latest apply-setters release tag was `go/apply-setters/v0.1.0` but the path to it is `functions/go/apply-setters/v0.1.0`.

**Comment by frankfarzan** [comment]
PR incorrectly refers to `searchreplace`.

**Comment by mengqiy** [comment]
> Can I also request that when you create a new release of the function to make sure that the tag matches the actual repo path? The latest apply-setters release tag was go/apply-setters/v0.1.0 but the path to it is functions/go/apply-setters/v0.1.0.

There is no plan to make the release tags match the full path. We want to make the release tags shorter.
@yhrn Why do you want to have that?

> apply-setters/api package holds core reusable logic.

This is out-of-date. There are no `api` package now.
We will not stop our users from using the package, but currently we don't plan to support the package as our API.

**Comment by yhrn** [comment]
> There is no plan to make the release tags match the full path. We want to make the release tags shorter.
> @yhrn Why do you want to have that?

@medyagh I'm a bit lost here, the point of my original ask was so that I could make a more complex function that also includes applying setters. So I would like to be able to do `go get github.com/GoogleContainerTools/kpt-functions-catalog/functions/go/apply-setters@vX.Y.Z`.

**Comment by phanimarupaka** [comment]
@yhrn The request was to separate it out of main package. You can reuse code in core applysetters package with this change.

**Comment by mengqiy** [comment]
@yhrn I got what you meant.
Even though we have git tag `go/apply-setters/v0.1.0`, go get doesn't allow us to do `go get github.com/mengqiy/kpt-functions-catalog/functions/go/apply-setters@go/apply-setters/v0.1.0`. The work around is use its corresponding SHA.
If we have a git tag `functions/go/apply-setters/v0.1.0` which matches the path, go get will allow us to do `go get github.com/mengqiy/kpt-functions-catalog/functions/go/apply-setters@v0.1.0`

**Comment by yhrn** [comment]
@phanimarupaka yes, and that is the most important thing for me, but I just thought it followed naturally that I would also like to be able to take a dependency on a specific release version so that is why I was a bit surprised at the question on why I wanted a tag matching the repo path of the function.

However, I could rephrase and ask if it would be possible to also create a full path tag that matches the release? For example if you release `go/apply-setters/v0.1.0` (or maybe something shorter in the future like `apply-setters/v0.1.0`) could you also tag the same commit with `functions/go/apply-setters/v0.1.0`? The second commit wouldn't need to be a release, just a plain tag.

**Comment by yhrn** [comment]
@mengqiy Yes exactly - didn't see your response before my previous comment.

**Comment by phanimarupaka** [comment]
@yhrn Couple of things here
1. Changing the naming pattern(to `functions/go/apply-setters/v0.1.0`) would solve the problem, talked to megqiy and we will be doing that. 
2. We version/release function packages based on the behavior changes(for e.g. the way we handle setter types) and not based on the api/code changes(e.g. If we change the name of a public function, we don't make a new release). As long as you are aware of that, you can fetch and reuse the core logic of the functions.

**Review by mengqiy — APPROVED** [review]

**Pull request merged**
