### PR TITLE
Added quotes to the annotations deletion-policy and local-config

### PR DESCRIPTION
**Pull request by cartyc**
Added quotes to the annotation values to prevent the following error with `ProjectServiceSet`

```
Error: 1 resource types could not be found in the cluster or as CRDs among the applied resources.

Resource types:
blueprints.cloud.google.com/v1alpha1, Kind=ProjectServiceSet
```

### CODE REVIEW

**Comment by bharathkkb** [comment]
x-ref: https://github.com/GoogleContainerTools/kpt/issues/2767

**Review by mengqiy — APPROVED** [review]

**Comment by cartyc** [comment]
@mengqiy Anything I can do to help get that failing test to pass?

**Comment by mengqiy** [comment]
Have you tried to rebase on the latest HEAD of master?

**Comment by cartyc** [comment]
I'll give it a go.

**Comment by cartyc** [comment]
@mengqiy rebase done.

**Pull request merged**
