### PR TITLE
add local-config annotation to local resources in examples

### PR DESCRIPTION
**Pull request by natasha41575**
Fixes https://github.com/GoogleContainerTools/kpt/issues/3844

Our examples should have the `local-config` annotation on Kptfile and functionConfigs so that they can be used correctly out of the box.

### CODE REVIEW

**Review by yuwenma — APPROVED** [review]
Nice Catch!!!

**Review by yuwenma — CHANGES_REQUESTED** [review]
Can you also update the CI e2e test?
Basically the test runs against each example under `./example` folder to verify if the output is expected (under the `.expected/diff.patch`). With the Kptfile changes, the expected output would then no longer matches.

**Comment by natasha41575** [comment]
> Can you also update the CI e2e test?

Done! Thanks for the pointer

**Comment by natasha41575** [comment]
@yuwenma Tests are passing now! Could you please merge when you get the chance?

**Review by yuwenma — APPROVED** [review]
thanks for the quick fixes

**Pull request merged**
